# Generated by Django 4.1.13 on 2024-04-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("home_link", models.CharField(max_length=200)),
                ("short_description", models.TextField()),
                ("long_deskription", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
